# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

minimal_mistakes_skin: "dirt"  # Apply the "dirt" skin for earthy tones

# Site Settings
locale: "en-US"
rtl: false  # Leave as false since you are using English (LTR language)
title: "Daniel Folino"
title_separator: "-"
subtitle: "Software Engineer & Chemical Engineering Student | University of Colorado Boulder"
name: "Daniel Folino"
description: "Welcome to my portfolio! A blend of software development, machine learning, and engineering expertise."  # Add a recruiter-friendly description
url: "https://dafo2334.github.io"  # Use your GitHub Pages URL
baseurl: ""  # Leave blank for root deployment
repository: "Dafo2334/dafo2334.github.io"  # Your GitHub repository

# Images and Teasers
teaser: ""  # Leave empty or add a path to an image
logo: ""  # Leave empty or add a path to your logo
masthead_title: "Daniel Folino | Portfolio"
breadcrumbs: true  # Enable breadcrumb navigation
words_per_minute: 200
enable_copy_code_button: true  # Enable copy-to-clipboard for code blocks
copyright: "Daniel Folino"
copyright_url: "https://dafo2334.github.io"

# Comments (set as false by default, change as needed)
comments:
  provider: false

# Analytics (optional)
analytics:
  provider: "google-gtag"  # Set this if you have a Google Analytics tracking code
  google:
    tracking_id: ""  # Your tracking ID
    anonymize_ip: true

# Social Sharing
twitter:
  username: ""  # Add your Twitter username
facebook:
  username: ""  # Add your Facebook username
  app_id: ""  # Add your Facebook app ID if applicable
og_image: ""  # Set a default image for Open Graph sharing

# Site Author
author:
  name: "Daniel Folino"
  avatar: ""  # Path to your avatar, e.g., "/assets/images/avatar.jpg"
  bio: "Computer Science and Chemical Engineering student with expertise in software engineering and machine learning."
  location: "Boulder, CO"
  email: ""  # Add your email or leave empty
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Dafo2334"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danielfolino"

# Footer links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Dafo2334"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danielfolino"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: ""  # Set your timezone, e.g., "America/Denver"

# Pagination with jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
