# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dirt"  # Use the dirt theme for earthy tones

# Site Settings
locale: "en-US"
title: "Daniel Folino"
title_separator: "-"
subtitle: "Software Engineer & Chemical Engineering Student | University of Colorado Boulder"
name: "Daniel Folino"
description: "Welcome to my portfolio! A blend of software development, machine learning, and engineering expertise."  # Catchy description for recruiters
url: "https://dafo2334.github.io"
baseurl: ""  # Leave blank for root deployment
repository: "Dafo2334/dafo2334.github.io"
logo: "/assets/images/logo.png"  # Customize if you have a logo
masthead_title: "Daniel Folino | Portfolio"
breadcrumbs: true  # Enable breadcrumb navigation for better UX
words_per_minute: 200
enable_copy_code_button: true  # Enable copy-to-clipboard for code blocks
copyright: "Daniel Folino"
copyright_url: "https://dafo2334.github.io"

# Comments (disabled by default, enable if needed)
comments:
  provider: false

# Site Author
author:
  name: "Daniel Folino"
  avatar: "/assets/images/bio-photo.jpg"  # Add your photo here
  bio: "Computer Science and Chemical Engineering student with expertise in software engineering, machine learning, and engineering principles."
  location: "Boulder, CO"
  email: "your.email@example.com"  # Replace with your email or leave blank
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your.email@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Dafo2334"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danielfolino"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Dafo2334"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danielfolino"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/yourTwitterHandle"  # Replace with your Twitter handle if available

# Search Configuration
search: true
search_provider: lunr
search_full_content: true

# SEO Related
google_site_verification: ""  # Optional, add if using Google Search Console
og_image: "/assets/images/og_image.png"  # Set default Open Graph image for social sharing

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Pagination Settings
paginate: 5
paginate_path: /page:num/

# Markdown and Sass Settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false  # Enable if you want comments on posts
      share: true
      related: true

# Compression
compress_html:
  clippings: all
  ignore:
    envs: development  # Disable compression in dev environment
